channels:
  - conda-forge
dependencies:
  - python=3.12
  - packaging>=24.1
  - pip
  - jupyterlab
  - xarray
  - rioxarray
  - matplotlib
  - numpy
  - pandas
  - netcdf4
  - geopandas
  - conda-build
  - contextily
  - tqdm
  - ipywidgets
  - dask
  - papermill
  - pip:
    - geonetworkx
    - podaac-data-subscriber
    - polyfit
    - ipyflow
